spring:
  profiles:
    active: keycloak
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace